### ISSUE TITLE
/tutorial.html#/43 reference to http://localhost:3000

### ISSUE THREAD

**Issue by elliotthilaire** [railsgirls-bne/railsgirls-bne.github.io#34]
> This created a new folder called 'pages', which you can find under app/views.
In that folder, you'll see a page called info.html.erb. Open it up.
You can customise the information in this page.
If you add /pages/info to your app URL now, you'll see this page. To see your new info page, take your browser to http://localhost:3000/pages/info.

There shouldn't be a mention to http://localhost:3000, this won't work when using cloud9

**Comment by JonathonMA** [comment]
When run server is used on c9 it has a nice "Your code is running at https://railsgirls-jonathonma-1.c9.io." message and link at the top of the console, maybe we could start from there and have them append the path? Or perhaps teach them hacking urls at the start?

Or even update the nav bar with a link to their info page.
