### ISSUE TITLE
/tutorial.html#/12 remove reference to starting server

### ISSUE THREAD

**Issue by elliotthilaire** [railsgirls-bne/railsgirls-bne.github.io#41]
> Lets start our server and see what we have created so far.
In the terminal type:
rails server
or use the 'Run Project' button at the top of the page of the Cloud9 IDE

I think this slide can be removed. By this stage the user has already started their server 3 times.
(once in cloud9-guides and twice on slide 7)

**Comment by JonathonMA** [comment]
#25 #26 #30 #41 are all "start the server" issues.

Given we're using c9, maybe we could just use the "Run Project" instruction, and `rails server` could be presented as the non-c9 alternative for those that want to on the first slide only.

**Comment by langsharpe** [comment]
We also should mention that the server needs to be restarted in places where the Gemfile is edited.
